<?php
/*
  Zerfrex (R) RAD ADM
  Zerfrex RAD for Administration & Data Management
  Copyright (c) 2013-2022 by Jorge A. Montes Pérez <jorge@zerfrex.com>
  All rights reserved. Todos los derechos reservados.

  Este software solo se puede usar bajo licencia del autor.
  El uso de este software no implica ni otorga la adquisición de
  derechos de explotación ni de propiedad intelectual o industrial.
 */


/**
 * @package data-gen
 */

namespace zfx;

/**
 * Human name generator
 */
class DataGenName extends DataGen
{

    const COMPLETE = 0;
    const NAME     = 1;
    const SURNAME  = 2;
    var     $surnames = array(
        'es' => array(
            'García',
            'González',
            'Rodríguez',
            'Fernández',
            'López',
            'Martínez',
            'Sánchez',
            'Pérez',
            'Gómez',
            'Martín',
            'Jiménez',
            'Ruiz',
            'Hernández',
            'Díaz',
            'Moreno',
            'Álvarez',
            'Muñoz',
            'Romero',
            'Alonso',
            'Gutiérrez',
            'Navarro',
            'Torres',
            'Domínguez',
            'Vázquez',
            'Ramos',
            'Gil',
            'Ramírez',
            'Serrano',
            'Blanco',
            'Molina',
            'Suárez',
            'Morales',
            'Ortega',
            'Delgado',
            'Castro',
            'Ortiz',
            'Rubio',
            'Marín',
            'Sanz',
            'Nuñez',
            'Iglesias',
            'Medina',
            'Garrido',
            'Santos',
            'Castillo',
            'Cortes',
            'Lozano',
            'Guerrero',
            'Cano',
            'Prieto',
            'Méndez',
            'Calvo',
            'Cruz',
            'Gallego',
            'Vidal',
            'León',
            'Herrera',
            'Márquez',
            'Peña',
            'Cabrera',
            'Flores',
            'Campos',
            'Vega',
            'Díez',
            'Fuentes',
            'Carrasco',
            'Caballero',
            'Nieto',
            'Reyes',
            'Aguilar',
            'Pascual',
            'Herrero',
            'Santana',
            'Lorenzo',
            'Hidalgo',
            'Montero',
            'Ibañez',
            'Gimenez',
            'Ferrer',
            'Durán',
            'Vicente',
            'Benítez',
            'Santiago',
            'Arias',
            'Mora',
            'Vargas',
            'Carmona',
            'Crespo',
            'Román',
            'Pastor',
            'Soto',
            'Sáez',
            'Velasco',
            'Soler',
            'Moya',
            'Esteban',
            'Parra',
            'Bravo',
            'Gallardo',
            'Rojas',
            'Pardo',
            'Merino',
            'Franco',
            'Espinosa',
            'Lara',
            'Izquierdo',
            'Rivas',
            'Rivera',
            'Silva',
            'Casado',
            'Arroyo',
            'Redondo',
            'Camacho',
            'Vera',
            'Rey',
            'Otero',
            'Luque',
            'Galán',
            'Montes',
            'Ríos',
            'Sierra',
            'Segura',
            'Carrillo',
            'Marcos',
            'Martí',
            'Soriano',
            'Mendoza',
            'Bernal',
            'Robles',
            'Vila',
            'Valero',
            'Palacios',
            'Exposito',
            'Benito',
            'Varela',
            'Andres',
            'Macias',
            'Pereira',
            'Guerra',
            'Heredia',
            'Bueno',
            'Roldan',
            'Mateo',
            'Villar',
            'Contreras',
            'Miranda',
            'Guillen',
            'Mateos',
            'Escudero',
            'Aguilera',
            'Casas',
            'Menendez',
            'Aparicio',
            'Rivero',
            'Estevez',
            'Beltran',
            'Padilla',
            'Calderon',
            'Rico',
            'Gracia',
            'Galvez',
            'Abad',
            'Conde',
            'Salas',
            'Jurado',
            'Quintana',
            'Plaza',
            'Acosta',
            'Aranda',
            'Blazquez',
            'Bermudez',
            'Roca',
            'Salazar',
            'Costa',
            'Santamaria',
            'Miguel',
            'Guzman',
            'Serra',
            'Villanueva',
            'Manzano',
            'Cuesta',
            'Tomas',
            'Hurtado',
            'Rueda',
            'Trujillo',
            'Avila',
            'Pacheco',
            'Simon',
            'De La Fuente',
            'Pons',
            'Lazaro',
            'Mesa',
            'Sancho',
            'Del Rio',
            'Escobar',
            'Millan',
            'Blasco',
            'Alarcon',
            'Luna',
            'Zamora'
        )
    );
    private $type     = 0;
    private $names    = array(
        'es' => array(
            'Adán',
            'Agustín',
            'Alberto',
            'Alejandro',
            'Alfonso',
            'Alfredo',
            'Andrés',
            'Antonio',
            'Armando',
            'Arturo',
            'Benito',
            'Benjamín',
            'Bernardo',
            'Carlos',
            'César',
            'Claudio',
            'Clemente',
            'Cristian',
            'Cristobal',
            'Daniel',
            'David',
            'Diego',
            'Eduardo',
            'Emilio',
            'Enrique',
            'Ernesto',
            'Esteban',
            'Federico',
            'Felipe',
            'Fernando',
            'Francisco',
            'Gabriel',
            'Gerardo',
            'Germán',
            'Gilberto',
            'Gonzalo',
            'Gregorio',
            'Guillermo',
            'Gustavo',
            'Hernán',
            'Homero',
            'Horacio',
            'Hugo',
            'Ignacio',
            'Jacobo',
            'Jaime',
            'Javier',
            'Jerónimo',
            'Jesús',
            'Joaquín',
            'Jorge',
            'José',
            'Juan',
            'Julio',
            'Lorenzo',
            'Lucas',
            'Luis',
            'Manuel',
            'Marcos',
            'Mariano',
            'Mario',
            'Martín',
            'Mateo',
            'Miguel',
            'Nicolás',
            'Octavio',
            'Óscar',
            'Pablo',
            'Patricio',
            'Pedro',
            'Rafael',
            'Ramiro',
            'Ramón',
            'Raúl',
            'Ricardo',
            'Roberto',
            'Rodrigo',
            'Rubén',
            'Salvador',
            'Samuel',
            'Sancho',
            'Santiago',
            'Sergio',
            'Teodoro',
            'Timoteo',
            'Tomás',
            'Vicente',
            'Víctor',
            'Adela',
            'Adriana',
            'Alejandra',
            'Alicia',
            'Amalia',
            'Ana',
            'Andrea',
            'Anita',
            'Ángela',
            'Barbara',
            'Beatriz',
            'Berta',
            'Blanca',
            'Caridad',
            'Carla',
            'Carlota',
            'Carmen',
            'Carolina',
            'Catalina',
            'Cecilia',
            'Clara',
            'Claudia',
            'Concepción',
            'Cristina',
            'Daniela',
            'Débora',
            'Diana',
            'Dolores',
            'Dorotea',
            'Elena',
            'Elisa',
            'Eloisa',
            'Elsa',
            'Elvira',
            'Emilia',
            'Esperanza',
            'Estela',
            'Ester',
            'Eva',
            'Florencia',
            'Francisca',
            'Gabriela',
            'Gloria',
            'Graciela',
            'Guadalupe',
            'Guillermina',
            'Inés',
            'Irene',
            'Isabel',
            'Isabela',
            'Josefina',
            'Juana',
            'Julia',
            'Laura',
            'Leonor',
            'Leticia',
            'Lilia',
            'Lorena',
            'Lourdes',
            'Lucia',
            'Luisa',
            'Luz',
            'Magdalena',
            'Manuela',
            'Marcela',
            'Margarita',
            'María',
            'Marilu',
            'Marisol',
            'Marta',
            'Mercedes',
            'Micaela',
            'Mónica',
            'Natalia',
            'Norma',
            'Olivia',
            'Patricia',
            'Pilar',
            'Ramona',
            'Raquel',
            'Rebeca',
            'Reina',
            'Rocio',
            'Rosa',
            'Rosalia',
            'Rosario',
            'Sara',
            'Silvia',
            'Sofia',
            'Soledad',
            'Sonia',
            'Susana',
            'Teresa',
            'Verónica',
            'Victoria',
            'Virginia',
            'Yolanda'
        )
    );

    // --------------------------------------------------------------------

    public function getType()
    {
        return $this->type;
    }

// --------------------------------------------------------------------

    public function setType($value)
    {
        $this->type = (int)$value;
    }

    // --------------------------------------------------------------------

    public function get($type = NULL)
    {
        if ($type !== NULL) {
            $this->setType($type);
        }
        $str = '';
        if ($this->type == self::COMPLETE) {
            $keyN = array_rand($this->names[$this->lang]);
            if ($this->lang == 'es') {
                $keyS1 = array_rand($this->surnames[$this->lang]);
                $keyS2 = array_rand($this->surnames[$this->lang]);
                $str   = $this->names[$this->lang][$keyN] . ' ' . $this->surnames[$this->lang][$keyS1] . ' ' . $this->surnames[$this->lang][$keyS2];
            }
        }
        elseif ($this->type == self::NAME) {
            $keyN = array_rand($this->names[$this->lang]);
            $str  = $this->names[$this->lang][$keyN];
        }
        else {
            if ($this->lang == 'es') {
                $keyS1 = array_rand($this->surnames[$this->lang]);
                $keyS2 = array_rand($this->surnames[$this->lang]);
                $str   = $this->surnames[$this->lang][$keyS1] . ' ' . $this->surnames[$this->lang][$keyS2];
            }
        }
        return $str;
    }
    // --------------------------------------------------------------------
}
